# Generated by Django 4.2 on 2023-04-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem", name="price", field=models.IntegerField(default=0),
        ),
    ]
