# Generated by Django 4.2 on 2023-04-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cartitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem", name="price", field=models.IntegerField(),
        ),
    ]
