# Generated by Django 4.2 on 2023-04-19 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_vendor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("OrderReceived", "OrderReceived"),
                            ("shipped", "shipped"),
                            ("Completed", "Completed"),
                        ],
                        default="OrderReceived",
                        max_length=100,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("product_price", models.FloatField()),
                ("ordered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order.payment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_product",
                        to="products.product",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order.shippingaddress",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buyproduct_variant",
                        to="products.variant",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_vendor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="sellproduct", name="payment",),
        migrations.RemoveField(model_name="sellproduct", name="product",),
        migrations.RemoveField(model_name="sellproduct", name="status",),
        migrations.RemoveField(model_name="sellproduct", name="user",),
        migrations.RemoveField(model_name="sellproduct", name="variant",),
        migrations.DeleteModel(name="BuyOrder",),
        migrations.DeleteModel(name="Sellproduct",),
        migrations.DeleteModel(name="Status",),
    ]
