# Generated by Django 4.2 on 2023-04-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_orderedproduct_payment_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="order_total", field=models.FloatField(default=0),
        ),
    ]
