# Generated by Django 4.2 on 2023-06-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_orderedproduct_is_rated_orderedproduct_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="order.payment",
            ),
        ),
    ]
