# Generated by Django 4.2 on 2023-06-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_vendor"),
        ("order", "0011_alter_order_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.reviewrating",
            ),
        ),
    ]
