# Generated by Django 4.2 on 2023-04-16 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="variants",),
        migrations.AddField(
            model_name="variant",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Variants",
                to="products.product",
            ),
        ),
    ]
