# Generated by Django 4.2 on 2023-04-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_variant_price_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Variant",
                to="products.product",
            ),
        ),
    ]
