# Generated by Django 4.2 on 2023-04-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0004_alter_variant_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
